### ISSUE TITLE
Ignore pages by template name

### ISSUE THREAD

**Issue by mrflix** [d4l-data4life/kirby3-static-site-generator#11]
I tried the static site generator on a website where I'm using some templates as blocks on a parent page. So in the end I don't need their generated `index.html`'s.

For example this is my `default.yml`:

```yaml
title: Page with Sections
columns:
  - width: 2/3
    sections:
      pages:
        headline: Sections
        type: pages
        template:
          - slideshow
          - text
          - image
          - product
          - rondel
          - gallery
          - product-gallery
```

So these subpages get boxed together on the page and are unimportant on their own.

Because of that I added an `ignored_templates` option to my local copy of your plugin to ignore these subpages:

```php
'd4l.static_site_generator.ignored_templates' => ['text',  'slideshow', 'text', 'image', 'product', 'rondel', 'gallery', 'product-gallery']
```

In the index.php hook I hand over the list to the generator:

```php
$ignoredTemplates = $kirby->option('d4l.static_site_generator.ignored_templates', []);

$staticSiteGenerator = new StaticSiteGenerator($kirby, null, $ignoredTemplates);
```

In the `StaticSiteGenerator` class constructor I added `$ignoredTemplates` to the parameters:

```php
public function __construct(App $kirby, array $pathsToCopy = null, array $ignoredTemplates = null)
```

and added this line after `$this->_pages = $kirby->site()->index();`:

```php
if ($ignoredTemplates) {
  $this->_pages = $this->_pages->not($this->_pages->filterBy('intendedTemplate', 'in', $ignoredTemplates));
}
```

I don't know if this option is relevant enough for the core but it might be a good lookup for someone googling it. So feel free to close it.
